---
torotin_repo_url: "https://github.com/Torotin/3x-ui_pro_Docker.git"
torotin_repo_version: "main"
torotin_project_src: "/srv/3x-ui_pro_Docker"
torotin_install_root: "/srv/docker-proxy"
torotin_destroy_docker_data: true
torotin_apply_firewall: true
torotin_apply_ssh: true
torotin_apply_network: true
torotin_run_self_update: false
torotin_doctor_verbose: false
torotin_hide_sensitive_logs: true
